# Generated by Django 5.2 on 2025-04-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='dummy', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
