# Generated by Django 5.2 on 2025-05-01 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_feedback', '0002_session_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_analysis', to='instant_feedback.studentanswerunit')),
            ],
        ),
    ]
