# Generated by Django 5.2 on 2025-05-01 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_feedback', '0003_metaanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_1', models.TextField()),
                ('answer_1', models.TextField()),
                ('question_2', models.TextField()),
                ('answer_2', models.TextField()),
                ('question_3', models.TextField()),
                ('answer_3', models.TextField()),
                ('question_4', models.TextField()),
                ('answer_4', models.TextField()),
                ('question_5', models.TextField()),
                ('answer_5', models.TextField()),
                ('question_6', models.TextField()),
                ('answer_6', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='instant_feedback.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
