# Generated by Django 5.2 on 2025-05-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_feedback', '0004_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='EijakushindanQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('model_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
