# Generated by Django 5.2 on 2025-05-09 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_feedback', '0006_studentanswerunit_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_analysis', to='instant_feedback.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
