# Generated by Django 5.2 on 2025-06-05 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instant_feedback', '0007_finalanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_by', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('subgenre', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
                ('importance', models.IntegerField()),
                ('answer', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
