# Generated by Django 5.2 on 2025-06-06 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0003_aifeedback_delete_grammaranswerunit'),
        ('material_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerunit',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_scheduler.schedulecomponent'),
        ),
    ]
