# Generated by Django 5.2 on 2025-06-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0004_answerunit_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('subgenre', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Markdownで記述された解説本文')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
