# Generated by Django 5.2 on 2025-06-09 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0005_grammarnote'),
        ('instant_feedback', '0007_finalanalysis'),
        ('material_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('advice', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_scheduler.schedulecomponent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instant_feedback.session')),
            ],
            options={
                'unique_together': {('session', 'component')},
            },
        ),
    ]
