# Generated by Django 5.2 on 2025-06-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0008_questionclipforgrammar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuestionForGrammar',
        ),
    ]
