# Generated by Django 5.2 on 2025-06-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0009_delete_userquestionforgrammar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionclipforgrammar',
            name='title',
        ),
    ]
