# Generated by Django 5.2 on 2025-06-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0010_remove_questionclipforgrammar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerunit',
            name='is_review_target',
            field=models.BooleanField(default=False),
        ),
    ]
