# Generated by Django 5.2 on 2025-07-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0011_answerunit_is_review_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarSubgenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="文法項目コード (例: 'SV', 'Relative_Clause')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="表示用名称 (例: 'SV文型', '関係代名詞')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='文法項目の詳細説明', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grammar_subgenre',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='grammar_subgenre_code_idx')],
            },
        ),
    ]
