# Generated by Django 5.2 on 2025-07-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0012_grammarsubgenre'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='grammarsubgenre',
            new_name='stra_gramma_code_cfaed5_idx',
            old_name='grammar_subgenre_code_idx',
        ),
        migrations.AlterModelTable(
            name='grammarsubgenre',
            table='stra_grammar_subgenre',
        ),
    ]
