# Generated by Django 5.2 on 2025-07-30 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0013_rename_grammar_subgenre_code_idx_stra_gramma_code_cfaed5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarquestion',
            name='subgenre_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='ai_writing.grammarsubgenre'),
        ),
    ]
