# Generated by Django 5.2 on 2025-07-30 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0014_grammarquestion_subgenre_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarquestion',
            name='subgenre',
            field=models.CharField(editable=False, help_text='旧文字列列（使用禁止）', max_length=100),
        ),
        migrations.AlterField(
            model_name='grammarquestion',
            name='subgenre_fk',
            field=models.ForeignKey(help_text='文法項目への参照（メイン使用）', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='ai_writing.grammarsubgenre'),
        ),
    ]
