# Generated by Django 5.2 on 2025-07-30 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0015_alter_grammarquestion_subgenre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarnote',
            name='subgenre_fk',
            field=models.ForeignKey(blank=True, db_column='subgenre_fk_id', help_text='supabase 既存列を利用', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='ai_writing.grammarsubgenre'),
        ),
    ]
