# Generated by Django 5.2 on 2025-07-31 00:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0016_grammarnote_subgenre_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StraSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_cycles', models.PositiveSmallIntegerField(default=5, help_text='目標周回数（通常5回）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('completed_cycles', models.PositiveSmallIntegerField(default=0, help_text='完了済み周回数', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('review', 'Review')], default='active', max_length=10)),
                ('session_date', models.DateField(help_text='セッション開始日（03:00切り上げ基準）')),
                ('started_at', models.DateTimeField(blank=True, help_text='セッション開始時刻', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='セッション完了時刻', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stra_sessions', to='ai_writing.grammarsubgenre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stra_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stra Session',
                'verbose_name_plural': 'Stra Sessions',
                'db_table': 'stra_sessions',
            },
        ),
        migrations.CreateModel(
            name='StraCycleSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_index', models.PositiveSmallIntegerField(help_text='周回番号（1から開始）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('session_id', models.CharField(help_text='旧互換用ユニークID（将来廃止予定）', max_length=100, unique=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='周回開始時刻（事前発行対応でNULL許容）', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='周回完了時刻', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stra_cycle_sessions', to='ai_writing.grammarsubgenre')),
                ('stra_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_sessions', to='ai_writing.strasession')),
            ],
            options={
                'verbose_name': 'Stra Cycle Session',
                'verbose_name_plural': 'Stra Cycle Sessions',
                'db_table': 'stra_cycle_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='strasession',
            index=models.Index(fields=['session_date'], name='stra_sessio_session_923c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='strasession',
            index=models.Index(fields=['material'], name='stra_sessio_materia_556f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='strasession',
            index=models.Index(fields=['user'], name='stra_sessio_user_id_ae4320_idx'),
        ),
        migrations.AddIndex(
            model_name='strasession',
            index=models.Index(fields=['user', 'session_date'], name='stra_sessio_user_id_58bead_idx'),
        ),
        migrations.AddConstraint(
            model_name='strasession',
            constraint=models.CheckConstraint(condition=models.Q(('completed_cycles__lte', models.F('target_cycles'))), name='stra_sessions_cycles_logic_check'),
        ),
        migrations.AddIndex(
            model_name='stracyclesession',
            index=models.Index(fields=['stra_session'], name='stra_cycle__stra_se_c5bfb9_idx'),
        ),
        migrations.AddIndex(
            model_name='stracyclesession',
            index=models.Index(fields=['material'], name='stra_cycle__materia_7d46e1_idx'),
        ),
        migrations.AddIndex(
            model_name='stracyclesession',
            index=models.Index(fields=['session_id'], name='stra_cycle__session_036ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='stracyclesession',
            index=models.Index(fields=['stra_session', 'cycle_index'], name='stra_cycle__stra_se_dd97fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='stracyclesession',
            constraint=models.UniqueConstraint(fields=('stra_session', 'cycle_index'), name='stra_cycle_sessions_unique_cycle'),
        ),
    ]
