# Generated by Django 5.2 on 2025-07-31 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0017_strasession_stracyclesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerunit',
            name='stra_cycle_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_units', to='ai_writing.stracyclesession'),
        ),
    ]
