# Generated by Django 5.2 on 2025-07-31 08:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0018_answerunit_stra_cycle_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_grade', models.CharField(choices=[('A', 'A - 優秀（ノーミス）'), ('B', 'B - 良好（軽微なミス）'), ('C', 'C - 要改善（理解不足）'), ('D', 'D - 不十分（大幅な間違い）')], max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('raw_evaluation_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='ai_writing.answerunit')),
            ],
            options={
                'indexes': [models.Index(fields=['overall_grade'], name='ai_writing__overall_0d2210_idx')],
            },
        ),
    ]
