# Generated by Django 5.2 on 2025-07-31 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0019_answerevaluation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerEvaluation',
            new_name='StraAnswerEvaluation',
        ),
        migrations.RenameIndex(
            model_name='straanswerevaluation',
            new_name='stra_answer_overall_7b0641_idx',
            old_name='ai_writing__overall_0d2210_idx',
        ),
        migrations.AlterModelTable(
            name='straanswerevaluation',
            table='stra_answerevaluation',
        ),
    ]
