# Generated by Django 5.2 on 2025-08-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0020_rename_answerevaluation_straanswerevaluation_and_more'),
        ('instant_feedback', '0007_finalanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerunit',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instant_feedback.session'),
        ),
    ]
