# Generated by Django 5.2 on 2025-04-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('user_prompt', models.TextField()),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('title_ja', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('summary_ja', models.TextField()),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
