# Generated by Django 5.2 on 2025-06-03 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField()),
                ('mode', models.CharField(choices=[('daily_for_one_week', '1週間毎日'), ('once', '一回のみ')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('app', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('detail', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='material_scheduler.schedule')),
            ],
        ),
    ]
