# Generated by Django 5.2 on 2025-05-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_full_name_customuser_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='line_display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='line_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
