# Generated by Django 5.2 on 2025-05-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_first_ai_writing_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='line_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='line_picture_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
