# Generated by Django 5.2 on 2025-07-22 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='教材タイトル')),
                ('subgenre', models.CharField(max_length=100, verbose_name='サブジャンル')),
                ('total_word_count', models.IntegerField(verbose_name='総語数')),
                ('total_sections', models.IntegerField(verbose_name='総セクション数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材一覧',
            },
        ),
        migrations.CreateModel(
            name='MaterialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(verbose_name='セクション番号')),
                ('text', models.TextField(verbose_name='英文')),
                ('translation', models.TextField(verbose_name='日本語訳')),
                ('word_count', models.IntegerField(verbose_name='語数')),
                ('audio_url', models.URLField(blank=True, max_length=500, verbose_name='音声URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tadoku.material', verbose_name='教材')),
            ],
            options={
                'verbose_name': '教材セクション',
                'verbose_name_plural': '教材セクション一覧',
                'ordering': ['section_number'],
                'unique_together': {('material', 'section_number')},
            },
        ),
    ]
