# Generated by Django 5.2 on 2025-07-25 06:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadoku', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TadokuSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('learning_context_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('target_cycles', models.PositiveIntegerField(default=5)),
                ('completed_cycles', models.PositiveIntegerField(default=0)),
                ('session_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tadoku.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tadoku_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tadoku_sessions',
                'ordering': ['-session_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'session_date'], name='tadoku_sess_user_id_0ec262_idx'), models.Index(fields=['learning_context_id'], name='tadoku_sess_learnin_b57461_idx')],
            },
        ),
    ]
