# Generated by Django 5.2 on 2025-07-26 01:09

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadoku', '0002_tadokusession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TadokuSessionStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_number', models.PositiveIntegerField()),
                ('sound_only_count', models.PositiveIntegerField(default=0)),
                ('text_count', models.PositiveIntegerField(default=0)),
                ('translation_count', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_stats', to='tadoku.tadokusession')),
            ],
            options={
                'db_table': 'tadoku_session_stats',
                'indexes': [models.Index(fields=['session'], name='tadoku_sess_session_086237_idx'), models.Index(fields=['cycle_number'], name='tadoku_sess_cycle_n_84cf3e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_pages', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('sound_only_count'), '+', models.F('text_count')), '+', models.F('translation_count')))), name='check_total_equals_sum')],
                'unique_together': {('session', 'cycle_number')},
            },
        ),
    ]
