# Generated by Django 5.2 on 2025-05-27 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveMaterialComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('question_text', models.TextField()),
                ('model_answer', models.TextField(blank=True, null=True)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('correct_choice', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_components', to='daily_material.curriculumday')),
            ],
        ),
        migrations.CreateModel(
            name='StaticMaterialComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_components', to='daily_material.curriculumday')),
            ],
        ),
    ]
