# Generated by Django 5.2 on 2025-08-22 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_id', models.CharField(db_index=True, max_length=64)),
                ('order_index', models.PositiveIntegerField(db_index=True)),
                ('target_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('not_done', 'Not done'), ('completed', 'Completed')], db_index=True, default='not_done', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_assignments', to='accounts.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAssignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('stra', 'Stra'), ('tadoku', 'Tadoku')], max_length=16)),
                ('material_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_done', 'Not done'), ('completed', 'Completed')], db_index=True, default='not_done', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assignment.dailyassignment')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_order_index', models.PositiveIntegerField(default=1)),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='accounts.enrollment')),
            ],
        ),
        migrations.AddIndex(
            model_name='dailyassignment',
            index=models.Index(fields=['enrollment', 'target_date'], name='assignment__enrollm_2c6dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyassignment',
            index=models.Index(fields=['curriculum_id', 'order_index'], name='assignment__curricu_fb2ad3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyassignment',
            unique_together={('enrollment', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='dailyassignmentitem',
            index=models.Index(fields=['assignment', 'status'], name='assignment__assignm_cc0ac7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyassignmentitem',
            unique_together={('assignment', 'component')},
        ),
    ]
