# Generated by Django 5.2 on 2025-08-22 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing', '0021_alter_answerunit_session'),
        ('assignment', '0001_initial'),
        ('tadoku', '0003_tadokusessionstats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyassignmentitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyassignmentitem',
            name='stra_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_items', to='ai_writing.strasession'),
        ),
        migrations.AddField(
            model_name='dailyassignmentitem',
            name='tadoku_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_items', to='tadoku.tadokusession'),
        ),
        migrations.AddConstraint(
            model_name='dailyassignmentitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stra_session__isnull', True), ('tadoku_session__isnull', True)), models.Q(('stra_session__isnull', False), ('tadoku_session__isnull', True)), models.Q(('stra_session__isnull', True), ('tadoku_session__isnull', False)), _connector='OR'), name='only_one_session_fk_filled'),
        ),
        migrations.AddConstraint(
            model_name='dailyassignmentitem',
            constraint=models.UniqueConstraint(fields=('assignment', 'component'), name='uniq_assignment_component'),
        ),
        migrations.RemoveField(
            model_name='dailyassignmentitem',
            name='session_id',
        ),
    ]
